version: '3.8'
services:
  react-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: always
    stdin_open: true # docker run의 -i 옵션. react 한정으로 필요함.
